# .github/workflows/deploy.yml

name: Build and Deploy to Firebase Hosting

# Trigger workflow on pushes to the main branch
on:
  push:
    branches:
      - main # Or your primary branch (e.g., master)

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest # Use Linux runner

    steps:
      # 1. Checkout the repository code
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Set up Node.js environment (use version consistent with Dockerfile)
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm' # Enable npm dependency caching

      # 3. Install dependencies securely and quickly
      - name: Install Dependencies
        run: npm ci

      # 4. Build the Vite application
      - name: Build Project
        run: npm run build # Output goes to 'dist'

      # 5. Deploy to Firebase Hosting
      - name: Deploy to Firebase Hosting
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}' # For deployment status checks
          firebaseServiceAccount: '' # Not needed when using FIREBASE_TOKEN
          channelId: live # Deploy to the production channel
          projectId: firestatsfrontend # !!! REPLACE THIS !!!
        env:
          FIREBASE_CLI_PREVIEWS: hostingchannels # Required by the deploy action
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }} # Use the secret